---
fail_fast: false

repos:
  # General hooks for various common checks.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: ^.*\.svd$
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=auto"]
      - id: trailing-whitespace

  # Hooks for formatting C++ code using clang-format.
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.6
    hooks:
      - id: clang-format
        files: \.(cpp|hpp)$

  # Linting for C++ code.
  - repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
      - id: cpplint
        args:
          - --linelength=120
          - --filter=+*,-whitespace/braces,-build/c++11,-runtime/references,-legal/copyright,-build/include_subdir,-readability/nolint
        files: \.cpp$|\.hpp$

  # Shell Format, clang-tidy NOLINT comments.
  - repo: https://github.com/kpada/pre-commit-hooks
    rev: v0.0.1
    hooks:
      - id: clang-tidy-nolint
      - id: shfmt
        args:
          - -i
          - "2"
          - -ci
          - -s

  # Formatting for CMake files.
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format

  # Spellcheck for various file types.
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [-w]
        files: ^.*\.(md|cpp|hpp|sh|yaml|yml)$

  # Hooks for formatting various file types using Prettier.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  # Linting for Markdown files.
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint

  # Checks for dead links in Markdown files.
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
      - id: markdown-link-check

  # Linting for YAML files.
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-s]

  # Linting for Dockerfile.
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
